# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-04 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodobot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='text_message',
        ),
    ]
